### ISSUE TITLE
Спорно, что это должно быть именно в этом интерфейсе. Получается, что любой AuthenticationProvider должен уметь обновлять токен (а в случае Basic никаких токенов нет)

### ISSUE THREAD

**Issue by coursar** [Egor-Slutskiy/web-app#2]
https://github.com/Egor-Slutskiy/web-app/blob/c2b022f6e9ca6f4404ce5c067890f7a98cb5a663/src/main/java/org/example/framework/security/AuthenticationProvider.java#L8

**Comment by Egor-Slutskiy** [comment]
Для Basic сделал отдельный провайдер, так что теперь по сути любой AuthenticationProvider должен уметь и обновлять токен.
