### ISSUE TITLE
А если handler тоже будет писать в ответ JSON? У вас в ответе будет два JSON'а?

### ISSUE THREAD

**Issue by coursar** [Egor-Slutskiy/web-app#3]
https://github.com/Egor-Slutskiy/web-app/blob/c2b022f6e9ca6f4404ce5c067890f7a98cb5a663/src/main/java/org/example/framework/filter/TokenAuthenticationFilter.java#L42

**Comment by Egor-Slutskiy** [comment]
Вынес из Json в X-Token header
